version: 2.1
jobs:
  unit-test:
    docker:
    - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - restore_cache:
        keys:
        - pkg-cache
    - run:
        name: Unit tests
        command: |
          go test ./...
    - save_cache:
        key: pkg-cache
        paths:
        - "/go/pkg"
  docker-build:
    docker:
    - image: circleci/golang:1.13
    steps:
    - checkout
    - setup_remote_docker:
        # Caching not available on free plan
        docker_layer_caching: false
    - run: |
        TAG=1.0.$CIRCLE_BUILD_NUM
        env GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build
        docker build -t armakuni/circleci-workflow-dashboard:$TAG .
        docker tag armakuni/circleci-workflow-dashboard:$TAG armakuni/circleci-workflow-dashboard:latest
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push armakuni/circleci-workflow-dashboard:latest
        docker push armakuni/circleci-workflow-dashboard:$TAG

workflows:
  version: 2
  deploy-docker:
    jobs:
    - unit-test:
        filters:
          branches:
            only: master
    - docker-build:
        requires:
        - unit-test
